/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package clases;

import java.util.ArrayList;
import java.util.InputMismatchException;
import java.util.Scanner;

public class Main {
    
    public static void main (String [] args) {
    	
    	ArrayList<Libro> catalogo = new ArrayList<Libro>();
    	
    	while(true) {
        int opcion =menu();
        switch (opcion) {
        case 1:
        	//Alta de Libro
        	//titulo:isbn:genero:autor:paginas
        	//alta(catalogo)
        	break;
        case 2:
        	//Lista de Libros
        	break;
        default:
        	break;
        }
    	}

    	
    }
    
    private  static int menu() {
    	int opcion =0;
    	
    	do {
    		System.out.println("Opciones:");
    		System.out.println("1. Alta de Libro");
    		System.out.println("2. Lista de Libros");
    		System.out.println("Introduce la opción:");
    		
    		opcion = leerOpcion(2);
    		
    	}while(opcion <=0);
    	
    	   	
    	return opcion;
    }
    
    private static int leerOpcion( int max) {
    	int opcion = -1;

    	try {
        	Scanner teclado = new Scanner(System.in);
    	opcion = teclado.nextInt();
    	if (opcion>max)
    		opcion=-1;
    	}catch(InputMismatchException e) {
    		System.out.println("Opcion incorrecta");
    	}
    	//teclado.close();
    	
    	
    	return opcion;
    }
    
    private static void alta(ArrayList<Libro> catalogo) {
    	//Leer de la entrada
    	System.out.println("Introduce los datos de un libro.");
    	System.out.println("Usa el formato \"\" ");
    	//titulo:isbn:genero:autor:paginas
    	//Procesar la entrada
    	//Crear el libro con los datos de la entrada
    	//Meter el libro en el catalogo
    }

    private static String leerCadena(){
    	String opcion = null;

    	try {
        	Scanner teclado = new Scanner(System.in);
    	opcion = teclado.next();
    	
    	}catch(InputMismatchException e) {
    		System.out.println("Opcion incorrecta");
    	}
    	//teclado.close();
    return null;
    }
}
